language: python

python:
  - 3.7

install:
  - pip install pylint
  - pip install -r requirements.txt

script:
  - find . -name "*.py" | xargs pylint --disable=fixme
  - python3 -m pytest test/run_tests.py
